# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

os: Visual Studio 2017

environment:
  global:
    CRATE_NAME: rsass
    #APPVEYOR_CACHE_SKIP_RESTORE: true

  matrix:
    # Stable channel
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
      TOOLCHAIN: msvc
      PLATFORM: x86_64
      
install:
  - if "%TOOLCHAIN%" == "msvc" if "%PLATFORM%" == "x86_64" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if "%TOOLCHAIN%" == "msys" set PATH=C:\msys64\mingw%MSYS_BITS%\bin;C:\msys64\usr\bin;%PATH%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %CHANNEL%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

test_script:
  # we don't run the "test phase" when doing deploys
  - if [%APPVEYOR_REPO_TAG%]==[false] ( cargo test )
  
cache:
  - C:\Users\appveyor\.cargo\registry
  - target

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
