[package]
name = "rsass"
version = "0.5.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]
categories = ["command-line-utilities", "web-programming"]
keywords = ["scss", "sass", "css"]
description = "Early-stage sass implementation in pure rust"
documentation = "https://docs.rs/rsass"
repository = "https://github.com/kaj/rsass"
readme = "README.md"
license = "MIT/Apache-2.0"

[[bin]]
name = "rsass"
doc = false

[dependencies]
clap = "^2.19"
lazy_static = "^0.2"
nom = "^3.2.0"
num-rational = "^0.1"
num-traits = "^0.1"
rand = "^0.3"

[badges]
travis-ci = { repository = "kaj/rsass" }
